# Creando el dataframe

In [5]:
# Definition of vectors
name <- c("Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune")
type <- c("Terrestrial planet", "Terrestrial planet", "Terrestrial planet", 
          "Terrestrial planet", "Gas giant", "Gas giant", "Gas giant", "Gas giant")
diameter <- c(0.382, 0.949, 1, 0.532, 11.209, 9.449, 4.007, 3.883)
rotation <- c(58.64, -243.02, 1, 1.03, 0.41, 0.43, -0.72, 0.67)
rings <- c(FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE)

# Create a data frame from the vectors
planets_df <-data.frame( name  ,  type,diameter,rotation,rings )

In [6]:
head(planets_df)
srt(planets_df)

name    type               diameter rotation rings
1 Mercury Terrestrial planet  0.382     58.64  FALSE
2 Venus   Terrestrial planet  0.949   -243.02  FALSE
3 Earth   Terrestrial planet  1.000      1.00  FALSE
4 Mars    Terrestrial planet  0.532      1.03  FALSE
5 Jupiter Gas giant          11.209      0.41   TRUE
6 Saturn  Gas giant           9.449      0.43   TRUE

ERROR: Error in srt(planets_df): no se pudo encontrar la función "srt"


## Selection of data frame elements

In [7]:
# The planets_df data frame from the previous exercise is pre-loaded
planets_df$name
# Print out diameter of Mercury (row 1, column 3)
planets_df[1,3]

# Print out data for Mars (entire fourth row)
planets_df[4,]

[1] Mercury Venus   Earth   Mars    Jupiter Saturn  Uranus  Neptune
Levels: Earth Jupiter Mars Mercury Neptune Saturn Uranus Venus

[1] 0.382

name type               diameter rotation rings
4 Mars Terrestrial planet 0.532    1.03     FALSE

In [14]:
# Select the rings variable from planets_df
rings_vector <- planets_df$rings

# Adapt the code to select all columns for planets with rings
planets_df[rings_vector, TRUE]

name    type      diameter rotation rings
5 Jupiter Gas giant 11.209    0.41    TRUE 
6 Saturn  Gas giant  9.449    0.43    TRUE 
7 Uranus  Gas giant  4.007   -0.72    TRUE 
8 Neptune Gas giant  3.883    0.67    TRUE

## Subset

In [10]:
# Select planets with diameter < 1
subset( planets_df , diameter < 1 )

name    type               diameter rotation rings
1 Mercury Terrestrial planet 0.382      58.64  FALSE
2 Venus   Terrestrial planet 0.949    -243.02  FALSE
4 Mars    Terrestrial planet 0.532       1.03  FALSE

## Ordenando datos
In data analysis you can sort your data according to a certain variable in the data set. In R, this is done with the help of the function order().

In [11]:
# Play around with the order function in the console
a = c(563434,3463,2,4247,8,2) 
order(a) 

[1] 3 6 5 2 4 1

## Ordenando el dataframe
La funcion order entrega un vector con las  posiciones de los elementos ordenados  , de esta manera podemos listar los elementos de un dataframe con este vector de indices. 

In [13]:
# Use order() to create positions
positions <-  order( planets_df$diameter )

# Use positions to sort planets_df
planets_df[ positions , ]

name    type               diameter rotation rings
1 Mercury Terrestrial planet  0.382     58.64  FALSE
4 Mars    Terrestrial planet  0.532      1.03  FALSE
2 Venus   Terrestrial planet  0.949   -243.02  FALSE
3 Earth   Terrestrial planet  1.000      1.00  FALSE
8 Neptune Gas giant           3.883      0.67   TRUE
7 Uranus  Gas giant           4.007     -0.72   TRUE
6 Saturn  Gas giant           9.449      0.43   TRUE
5 Jupiter Gas giant          11.209      0.41   TRUE

# Lists, why would you need them?
Congratulations! At this point in the course you are already familiar with:

Vectors (one dimensional array): can hold numeric, character or logical values. The elements in a vector all have the same data type.
Matrices (two dimensional array): can hold numeric, character or logical values. The elements in a matrix all have the same data type.
Data frames (two-dimensional objects): can hold numeric, character or logical values. Within a column all elements have the same data type, but different columns can be of different data type.

## Creating a list

In [16]:
# Vector with numerics from 1 up to 10
my_vector <- 1:10 

# Matrix with numerics from 1 up to 9
my_matrix <- matrix(1:9, ncol = 3)

# First 10 elements of the built-in data frame mtcars
my_df <- mtcars[1:10,]

# Construct list with these different elements:
my_list <-list(my_vector , my_matrix , my_df)
#my_list

[[1]]
 [1]  1  2  3  4  5  6  7  8  9 10

[[2]]
     [,1] [,2] [,3]
[1,]    1    4    7
[2,]    2    5    8
[3,]    3    6    9

[[3]]
                   mpg cyl  disp  hp drat    wt  qsec vs am gear carb
Mazda RX4         21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4
Mazda RX4 Wag     21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4
Datsun 710        22.8   4 108.0  93 3.85 2.320 18.61  1  1    4    1
Hornet 4 Drive    21.4   6 258.0 110 3.08 3.215 19.44  1  0    3    1
Hornet Sportabout 18.7   8 360.0 175 3.15 3.440 17.02  0  0    3    2
Valiant           18.1   6 225.0 105 2.76 3.460 20.22  1  0    3    1
Duster 360        14.3   8 360.0 245 3.21 3.570 15.84  0  0    3    4
Merc 240D         24.4   4 146.7  62 3.69 3.190 20.00  1  0    4    2
Merc 230          22.8   4 140.8  95 3.92 3.150 22.90  1  0    4    2
Merc 280          19.2   6 167.6 123 3.92 3.440 18.30  1  0    4    4

## Lista con etiquetas

In [25]:
# Vector with numerics from 1 up to 10
my_vector <- 1:10 

# Matrix with numerics from 1 up to 9
my_matrix <- matrix(1:9, ncol = 3)

# First 10 elements of the built-in data frame mtcars
my_df <- mtcars[1:10,]

# Adapt list() call to give the components names
my_list <- list(my_vector, my_matrix, my_df)
names(my_list) = c("uno", "dos"  , "tres" )

# Print out my_list
#my_list

## Seleccionando elementos de una lista 
Para seleccionar elementos de una lista se puede utilizar [[]] o simplente $

```  
    my_list[["dos"]]  
    my_list$dos
```
Cuando es necesario acceder a un index especifico agrega un [] al final de la sentencia 

```
    my_list[["dos"]][2]
    my_list$dos[2]
```



In [24]:
my_list$dos[1,]

[1] 1 4 7

## Agregando elementos a la lista 
Simplemente sera necesario crear una nueva lista con los elementos a agegar por medio de un vector c() 

In [29]:
# We forgot something; add the year to shining_list
mueva_lista <- c(my_list , new_label = 123423123123)

# Have a look at shining_list_full
str(mueva_lista)

List of 4
 $ uno      : int [1:10] 1 2 3 4 5 6 7 8 9 10
 $ dos      : int [1:3, 1:3] 1 2 3 4 5 6 7 8 9
 $ tres     :'data.frame':	10 obs. of  11 variables:
  ..$ mpg : num [1:10] 21 21 22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2
  ..$ cyl : num [1:10] 6 6 4 6 8 6 8 4 4 6
  ..$ disp: num [1:10] 160 160 108 258 360 ...
  ..$ hp  : num [1:10] 110 110 93 110 175 105 245 62 95 123
  ..$ drat: num [1:10] 3.9 3.9 3.85 3.08 3.15 2.76 3.21 3.69 3.92 3.92
  ..$ wt  : num [1:10] 2.62 2.88 2.32 3.21 3.44 ...
  ..$ qsec: num [1:10] 16.5 17 18.6 19.4 17 ...
  ..$ vs  : num [1:10] 0 0 1 1 0 1 0 1 1 1
  ..$ am  : num [1:10] 1 1 1 0 0 0 0 0 0 0
  ..$ gear: num [1:10] 4 4 4 3 3 3 3 4 4 4
  ..$ carb: num [1:10] 4 4 1 1 2 1 4 2 2 4
 $ new_label: num 1.23e+11


# Matrices 

You can construct a matrix in R with the matrix() function. Consider the following example:

> matrix(1:9, byrow = TRUE, nrow = 3)

In the matrix() function:

- The first argument is the collection of elements that R will arrange into the rows and columns of the matrix. Here, we use 1:9 which is a shortcut for c(1, 2, 3, 4, 5, 6, 7, 8, 9).
- The argument byrow indicates that the matrix is filled by the rows. If we want the matrix to be filled by the columns, we just place byrow = FALSE.
- The third argument nrow indicates that the matrix should have three rows.

In [1]:
matrix( 1:9 , byrow=T , nrow=3 )

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [6]:
# Box office Star Wars (in millions!)
new_hope <- c(460.998, 314.4)
empire_strikes <- c(290.475, 247.900)
return_jedi <- c(309.306, 165.8)

# Create box_office
box_office <- c( new_hope,empire_strikes,return_jedi )

# Construct star_wars_matrix
star_wars_matrix <- matrix(box_office, byrow=T , nrow=3 )
star_wars_matrix

[,1]    [,2] 
[1,] 460.998 314.4
[2,] 290.475 247.9
[3,] 309.306 165.8

## Renombrando la matriz

Similar to vectors, you can add names for the rows and the columns of a matrix

> rownames(my_matrix) <- row_names_vector <br>
> colnames(my_matrix) <- col_names_vector

In [8]:
col_names = c("US", "non-US")
fil_names = c("new_hope", "empire_strikes", "return_jedi")

In [9]:
colnames(star_wars_matrix) = col_names 
rownames(star_wars_matrix) = fil_names 

In [15]:
star_wars_matrix

US      non-US
new_hope       460.998 314.4 
empire_strikes 290.475 247.9 
return_jedi    309.306 165.8

## Sumas totales
Esta función calcula los totales de cada fila , retornando un vector.
> rowSums(my_matrix)

In [13]:
rowSums(star_wars_matrix)

new_hope empire_strikes    return_jedi 
       775.398        538.375        475.106

## Agregando una colunma
Cbind se utiliza para agregar una columna o varias  a una matriz ej.

> big_matrix <- cbind(matrix1, matrix2, vector1 ...)



In [16]:
 # vector con la sumas de los totales 
worldwide_vector <- rowSums(star_wars_matrix)

# Agregnado la nueva variable a la matriz 
all_wars_matrix <- cbind(star_wars_matrix , worldwide_vector)

all_wars_matrix

US      non-US worldwide_vector
new_hope       460.998 314.4  775.398         
empire_strikes 290.475 247.9  538.375         
return_jedi    309.306 165.8  475.106

## Agregando una fila
De la misma forma se puede agregar una fila o varias con la funcion rbin ej :
> big_matrix <- rbind(matrix1, matrix2, vector1 ...)



## Seleccion de elementos dentro de una matriz.

You should therefore use a comma to separate the rows you want to select from the columns. For example:

- my_matrix[1,2] selects the element at the first row and second column.
- my_matrix[1:3,2:4] results in a matrix with the data on the rows 1, 2, 3 and columns 2, 3, 4.

If you want to select all elements of a row or a column, no number is needed before or after the comma, respectively:

- my_matrix[,1] selects all elements of the first column.
- my_matrix[1,] selects all elements of the first row.

In [19]:
# Select the non-US revenue for all movies
non_us_all <- all_wars_matrix[,2]
  
# Average non-US revenue
mean(non_us_all)
  
# Select the non-US revenue for first two movies
non_us_some <- all_wars_matrix[1:2,2]
  
# Average non-US revenue for first two movies
mean(non_us_some)

[1] 242.7

[1] 281.15

In [21]:
# Estimate the visitors
visitors <-  all_wars_matrix / 5
visitors

US      non-US worldwide_vector
new_hope       92.1996 62.88  155.0796        
empire_strikes 58.0950 49.58  107.6750        
return_jedi    61.8612 33.16   95.0212

# Factor , ¿Qué es? y ¿Cómo utilizarlo?.
Factor hacer referencia a una variable de tipo categorica , es decir que puede tomar valores finitos la diferencia cin una variable continua es que puede contener infinitos valores.



In [22]:
# Sex vector
sex_vector <- c("Male", "Female", "Female", "Male", "Male")

# Convert sex_vector to a factor
factor_sex_vector <- factor(sex_vector)

# Print out factor_sex_vector
factor_sex_vector

[1] Male   Female Female Male   Male  
Levels: Female Male

## Tipos de variables categóricas
- Nominal

No implica un orden. Ej:Perro , Gato , Ave.
- Ordinal

Si implica un orden natural. Ej: Alto , Medio , Bajo.

Factor agrupa las categorias con el nombre de levels , el nombre de cada una puede ser asignado si se requiere por raznes de legivilidad con la funcion levels().
Imagina que el siguente vector contiene sufijos para las categorias hombre y mujer :

In [28]:
survey_vector <- c("M", "F", "F", "M", "M")
factor_survey_vector = factor(survey_vector)

#### Cuidado ! 
Tenga en cuenta que al asignar las categorias con levels, pues se asignarán en orden alfebetico.

Para este caso se ocuparia:

In [30]:
# Build factor_survey_vector with clean levels
survey_vector <- c("M", "F", "F", "M", "M")
factor_survey_vector <- factor(survey_vector)
levels(factor_survey_vector) <- c("Female", "Male")
factor_survey_vector

# Generate summary for survey_vector
summary(survey_vector)

# Generate summary for factor_survey_vector
summary(factor_survey_vector)

[1] Male   Female Female Male   Male  
Levels: Female Male

   Length     Class      Mode 
        5 character character 

Female   Male 
     2      3

## Comparando categorías ordenadas
Al crear una categoría como factores posible especificar su orden con "ordered = TRUE".


In [33]:
# Create factor_speed_vector
speed_vector <- c("medium", "slow", "slow", "medium", "fast")
factor_speed_vector <- factor(speed_vector, ordered = TRUE, levels = c("slow", "medium", "fast"))

# Factor value for second data analyst
da2 <- factor_speed_vector[2]

# Factor value for fifth data analyst
da5 <- factor_speed_vector[5]

# Is data analyst 2 faster than data analyst 5?
da2 > da5
#

[1] FALSE